import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.List;
import java.util.concurrent.*;

/** Linux/Windows desktop companion for the Sonnenbank Android app. */
public final class SolarbankDesktop {
    private static final Color BG=new Color(5,13,25), CARD=new Color(13,29,48), BORDER=new Color(33,70,103), INK=new Color(230,242,255), MUTED=new Color(137,164,189), GREEN=new Color(35,244,174), BLUE=new Color(41,170,255), YELLOW=new Color(255,198,50), PURPLE=new Color(178,103,255), ORANGE=new Color(255,143,67);
    private final DesktopPreferences prefs=new DesktopPreferences();
    private final HistoryStore history=new HistoryStore();
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final ScheduledExecutorService scheduler=Executors.newSingleThreadScheduledExecutor();
    private JFrame frame;private JPanel page,devicePanel,plugPanel;private JLabel connectionLabel,updatedLabel,myStromStatus;private JComboBox<String> systemSelect;private JButton loginButton;private JTextField myStromIpField;
    private final ArrayList<String> siteIds=new ArrayList<>();private final ArrayList<String> siteNames=new ArrayList<>();private JSONArray devices=new JSONArray();private AnkerCloudClient client;private AnkerMqttLiveClient mqtt;private String selectedSite="";private JSONObject scene=new JSONObject();private final LinkedHashMap<String,GraphCard> plugCards=new LinkedHashMap<>();
    private GraphCard energyCard,batteryCard,meterPowerCard,meterVoltageCard,myStromChart;

    public static void main(String[] args){SwingUtilities.invokeLater(()->new SolarbankDesktop().open());}
    private void open(){frame=new JFrame("Sonnenbank · Solarbank Live");frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);frame.setMinimumSize(new Dimension(1120,780));frame.setSize(1450,1000);frame.setLocationRelativeTo(null);frame.getContentPane().setBackground(BG);showLogin();frame.setVisible(true);if(!prefs.getString("auth_token","").isBlank()&&!prefs.getString("user_token","").isBlank())restoreSession();}

    private void showLogin(){JPanel root=new JPanel(new BorderLayout(0,22));root.setBackground(BG);root.setBorder(new EmptyBorder(24,32,28,32));JPanel top=new JPanel(new BorderLayout());top.setOpaque(false);JLabel brand=label("☀  Sonnenbank",29,INK,true);top.add(brand,BorderLayout.WEST);JLabel sub=label("SOLAR LIVE · DESKTOP",12,GREEN,true);top.add(sub,BorderLayout.SOUTH);root.add(top,BorderLayout.NORTH);
        JPanel center=new JPanel(new GridBagLayout());center.setOpaque(false);JPanel card=cardPanel();card.setLayout(new BoxLayout(card,BoxLayout.Y_AXIS));card.setBorder(new EmptyBorder(30,34,30,34));card.setPreferredSize(new Dimension(430,390));card.add(label("Bei Anker SOLIX anmelden",24,INK,true));card.add(Box.createVerticalStrut(8));card.add(label("Deine Solarbank, Messwerte und Energieverläufe",13,MUTED,false));card.add(Box.createVerticalStrut(24));JTextField email=new JTextField(prefs.getString("email",""));styleInput(email);card.add(email);card.add(Box.createVerticalStrut(12));JPasswordField password=new JPasswordField();styleInput(password);card.add(password);card.add(Box.createVerticalStrut(18));loginButton=new JButton("Anmelden und Systeme laden");styleButton(loginButton,GREEN);loginButton.setForeground(BG);card.add(loginButton);card.add(Box.createVerticalStrut(14));connectionLabel=label("Das Passwort wird nicht auf diesem PC gespeichert.",12,MUTED,false);card.add(connectionLabel);card.add(Box.createVerticalGlue());center.add(card);root.add(center,BorderLayout.CENTER);
        loginButton.addActionListener(e->login(email.getText().trim(),new String(password.getPassword())));password.addActionListener(e->loginButton.doClick());replaceRoot(root);}

    private void login(String email,String password){if(email.isBlank()||password.isBlank()){connectionLabel.setText("E-Mail und Passwort eingeben.");return;}loginButton.setEnabled(false);connectionLabel.setText("Anmeldung wird durchgeführt …");worker.execute(()->{try{AnkerCloudClient fresh=new AnkerCloudClient();AnkerCloudClient.Result result=fresh.loginAndGetSites(email,password);JSONArray loaded=fresh.getUserDevices();JSONArray bound=fresh.getBoundDevices();SwingUtilities.invokeLater(()->{client=fresh;devices=mergeDevices(loaded,bound);prefs.putString("auth_token",client.authToken());prefs.putString("user_token",client.userToken());prefs.putString("nickname",result.nickname);prefs.putString("email",email);showDashboard(result.sites);});}catch(Exception ex){SwingUtilities.invokeLater(()->{loginButton.setEnabled(true);connectionLabel.setText("Anmeldung fehlgeschlagen: "+safe(ex));});}});}
    private void restoreSession(){worker.execute(()->{try{client=new AnkerCloudClient(prefs.getString("auth_token",""),prefs.getString("user_token",""));AnkerCloudClient.Result result=client.getSites(prefs.getString("nickname","Sonnenbank"));JSONArray loaded=client.getUserDevices(),bound=client.getBoundDevices();devices=mergeDevices(loaded,bound);SwingUtilities.invokeLater(()->showDashboard(result.sites));}catch(Exception ex){prefs.remove("auth_token");prefs.remove("user_token");SwingUtilities.invokeLater(this::showLogin);}});}

    private void showDashboard(JSONArray sites){siteIds.clear();siteNames.clear();for(int i=0;i<sites.length();i++){JSONObject s=sites.optJSONObject(i);if(s==null)continue;String id=first(s,"site_id","id");if(id.isBlank())continue;siteIds.add(id);siteNames.add(firstOr(s,"Solarbank-System "+(i+1),"site_name","name","home_name"));}if(siteIds.isEmpty()){showLogin();connectionLabel.setText("Im Anker-Konto wurde kein System gefunden.");return;}
        JPanel root=new JPanel(new BorderLayout());root.setBackground(BG);JPanel top=new JPanel(new BorderLayout(14,0));top.setBackground(new Color(7,19,34));top.setBorder(new EmptyBorder(14,24,14,24));JLabel brand=label("☀  Sonnenbank 4 Pro",24,INK,true);top.add(brand,BorderLayout.WEST);JPanel controls=new JPanel(new FlowLayout(FlowLayout.RIGHT,10,0));controls.setOpaque(false);systemSelect=new JComboBox<>(siteNames.toArray(new String[0]));systemSelect.setFont(new Font("SansSerif",Font.PLAIN,14));systemSelect.setBackground(CARD);systemSelect.setForeground(INK);controls.add(systemSelect);connectionLabel=label("● Verbinde …",13,GREEN,true);controls.add(connectionLabel);JButton refresh=new JButton("Aktualisieren");styleButton(refresh,BLUE);controls.add(refresh);JButton logout=new JButton("Abmelden");styleButton(logout,BORDER);controls.add(logout);top.add(controls,BorderLayout.EAST);root.add(top,BorderLayout.NORTH);
        page=new JPanel();page.setBackground(BG);page.setBorder(new EmptyBorder(17,22,30,22));page.setLayout(new BoxLayout(page,BoxLayout.Y_AXIS));JScrollPane scroll=new JScrollPane(page);scroll.setBorder(null);scroll.getViewport().setBackground(BG);scroll.getVerticalScrollBar().setUnitIncrement(24);root.add(scroll,BorderLayout.CENTER);buildDashboardContent();replaceRoot(root);
        systemSelect.addActionListener(e->{int i=systemSelect.getSelectedIndex();if(i>=0&&i<siteIds.size()){selectedSite=siteIds.get(i);loadSelectedSite();}});refresh.addActionListener(e->loadSelectedSite());logout.addActionListener(e->{if(mqtt!=null)mqtt.stop();prefs.remove("auth_token");prefs.remove("user_token");showLogin();});systemSelect.setSelectedIndex(0);selectedSite=siteIds.get(0);startMqtt();scheduler.scheduleAtFixedRate(this::poll,30,30,TimeUnit.SECONDS);scheduler.scheduleAtFixedRate(this::pollMyStrom,5,10,TimeUnit.SECONDS);}

    private void buildDashboardContent(){JPanel hero=cardPanel();hero.setLayout(new BorderLayout(20,14));hero.setBorder(new EmptyBorder(17,20,17,20));JPanel heroHead=new JPanel(new BorderLayout());heroHead.setOpaque(false);heroHead.add(label("ENERGIEFLUSS · LIVE",13,GREEN,true),BorderLayout.WEST);updatedLabel=label("Warte auf Messwerte",12,MUTED,false);heroHead.add(updatedLabel,BorderLayout.EAST);hero.add(heroHead,BorderLayout.NORTH);JPanel flow=new JPanel(new GridLayout(1,5,10,0));flow.setOpaque(false);String[] names={"PV-ERZEUGUNG","AKKU","HAUSVERBRAUCH","NETZBEZUG","EINSPEISUNG"};Color[] colors={YELLOW,GREEN,BLUE,PURPLE,ORANGE};for(int i=0;i<names.length;i++)flow.add(metricTile(names[i],colors[i],i));hero.add(flow,BorderLayout.CENTER);page.add(hero);
        energyCard=new GraphCard("▥  Energiefluss & Leistung",new String[]{"flow.pv","flow.home","flow.battery","flow.grid"},new String[]{"PV","Haus","Akku","Netz"},new Color[]{YELLOW,BLUE,GREEN,PURPLE},"power");page.add(energyCard);batteryCard=new GraphCard("▣  Batterieladestand",new String[]{"battery.soc"},new String[]{"Ladezustand"},new Color[]{GREEN},"percent");page.add(batteryCard);buildMyStromCard();
        meterPowerCard=new GraphCard("⚡  Smart Meter · L1 / L2 / L3 / Gesamt",new String[]{"meter.l1","meter.l2","meter.l3","meter.total"},new String[]{"L1","L2","L3","Gesamt"},new Color[]{YELLOW,BLUE,GREEN,PURPLE},"power");page.add(meterPowerCard);meterVoltageCard=new GraphCard("⌁  Spannung je Phase",new String[]{"meter.v1","meter.v2","meter.v3"},new String[]{"L1","L2","L3"},new Color[]{YELLOW,BLUE,GREEN},"voltage");page.add(meterVoltageCard);
        JLabel devicesHeader=label("GERÄTE · MESSWERTE",13,MUTED,true);devicesHeader.setBorder(new EmptyBorder(20,2,8,2));page.add(devicesHeader);devicePanel=new JPanel();devicePanel.setOpaque(false);devicePanel.setLayout(new BoxLayout(devicePanel,BoxLayout.Y_AXIS));page.add(devicePanel);JLabel plugHeader=label("SMART PLUG GEN 2 · LEISTUNGSVERLAUF",13,MUTED,true);plugHeader.setBorder(new EmptyBorder(20,2,8,2));page.add(plugHeader);plugPanel=new JPanel();plugPanel.setOpaque(false);plugPanel.setLayout(new BoxLayout(plugPanel,BoxLayout.Y_AXIS));page.add(plugPanel);}

    private JPanel metricTile(String name,Color accent,int i){JPanel tile=cardPanel();tile.setLayout(new BoxLayout(tile,BoxLayout.Y_AXIS));tile.setBorder(new EmptyBorder(13,15,13,15));tile.add(label(name,11,MUTED,true));JLabel value=label("—",23,accent,true);tile.add(Box.createVerticalStrut(8));tile.add(value);tile.add(Box.createVerticalStrut(3));tile.add(label(i==1?"Akku-Ladeleistung":i==3?"Leistung aus dem Netz":i==4?"Leistung ins Netz":"Aktuelle Leistung",11,MUTED,false));metricValues.add(value);return tile;}
    private final ArrayList<JLabel> metricValues=new ArrayList<>();
    private JPanel metricSummary(String icon,String title,String initial,Color accent){JPanel p=cardPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBorder(new EmptyBorder(13,15,13,15));p.add(label(icon+"  "+title,12,MUTED,true));p.add(Box.createVerticalStrut(7));p.add(label(initial,19,accent,true));return p;}

    private void buildMyStromCard(){JPanel box=cardPanel();box.setLayout(new BorderLayout(8,8));box.setBorder(new EmptyBorder(13,16,13,16));JPanel header=new JPanel(new BorderLayout());header.setOpaque(false);header.add(label("☀  Weitere PV · myStrom",15,INK,true),BorderLayout.WEST);JPanel controls=new JPanel(new FlowLayout(FlowLayout.RIGHT,7,0));controls.setOpaque(false);myStromIpField=new JTextField(prefs.getString("mystrom_ip",""),14);styleInput(myStromIpField);myStromIpField.setPreferredSize(new Dimension(170,34));controls.add(myStromIpField);JButton save=new JButton("Verbinden");styleButton(save,GREEN);save.setForeground(BG);controls.add(save);myStromStatus=label("Lokale myStrom-Steckdose",11,MUTED,false);controls.add(myStromStatus);header.add(controls,BorderLayout.EAST);box.add(header,BorderLayout.NORTH);myStromChart=new GraphCard("myStrom · Leistung",new String[]{"mystrom."+prefs.getString("mystrom_ip","")},new String[]{"Leistung"},new Color[]{YELLOW},"power");box.add(myStromChart,BorderLayout.CENTER);save.addActionListener(e->{String ip=myStromIpField.getText().trim();if(!validIPv4(ip)){myStromStatus.setText("Bitte lokale IPv4-Adresse prüfen");return;}prefs.putString("mystrom_ip",ip);myStromChart.keys[0]="mystrom."+ip;myStromStatus.setText("Verbinde …");pollMyStrom();});page.add(box);}

    private void loadSelectedSite(){if(selectedSite.isBlank()||client==null)return;connectionLabel.setText("● Lade System …");worker.execute(this::poll);}
    private void poll(){if(client==null||selectedSite.isBlank())return;try{JSONObject data=client.getSceneInfo(selectedSite);JSONObject mqttBank=findMqtt("AE103");JSONObject mqttMeter=findMqtt("AE1X0");JSONObject bank=data.optJSONObject("solarbank_info");if(bank==null)bank=new JSONObject();JSONObject grid=data.optJSONObject("grid_info");if(grid==null){grid=new JSONObject();data.put("grid_info",grid);}if(mqttBank!=null){if(mqttBank.has("photovoltaic_power"))bank.put("total_photovoltaic_power",mqttBank.optDouble("photovoltaic_power"));if(mqttBank.has("battery_power_signed"))bank.put("total_battery_power_signed",mqttBank.optDouble("battery_power_signed"));if(mqttBank.has("home_demand"))data.put("home_load_power",mqttBank.optDouble("home_demand"));}
            if(mqttMeter!=null)for(int p=1;p<=3;p++){String key="grid_power_signed_l"+p;if(mqttMeter.has(key))grid.put(key,mqttMeter.optDouble(key));String voltage="voltage_l"+p;if(mqttMeter.has(voltage))grid.put(voltage,mqttMeter.optDouble(voltage));}double pv=num(bank,"total_photovoltaic_power","total_pv_input_power"),home=num(data,"home_load_power","to_home_load"),battery=num(bank,"total_battery_power_signed","total_charging_power"),imp=num(grid,"grid_to_home_power"),exp=num(grid,"photovoltaic_to_grid_power");double signed=Double.isFinite(imp)||Double.isFinite(exp)?(Double.isFinite(imp)?imp:0)-(Double.isFinite(exp)?exp:0):num(grid,"grid_power_signed");if(mqttMeter!=null)signed=num(mqttMeter,"grid_power_signed");double soc=num(bank,"total_battery_power");if(soc<0||soc>100||!Double.isFinite(soc)){JSONArray batteries=bank.optJSONArray("solarbank_list");if(batteries!=null&&batteries.length()>0){JSONObject first=batteries.optJSONObject(0);if(first!=null)soc=num(first,"battery_soc");}}if(soc>0&&soc<=1)soc*=100;long now=System.currentTimeMillis();record("flow.pv",pv,now);record("flow.home",home,now);record("flow.battery",battery,now);record("flow.grid",signed,now);record("battery.soc",soc,now);
            double total=0;boolean has=false;for(int p=1;p<=3;p++){double watts=num(grid,"grid_power_signed_l"+p);if(!Double.isFinite(watts)&&mqttMeter!=null)watts=num(mqttMeter,"grid_power_signed_l"+p);if(Double.isFinite(watts)){has=true;total+=watts;record("meter.l"+p,watts,now);}double volts=num(grid,"voltage_l"+p);if(!Double.isFinite(volts)&&mqttMeter!=null)volts=num(mqttMeter,"voltage_l"+p);record("meter.v"+p,volts,now);}record("meter.total",has?total:signed,now);recordPlugs(now);
            JSONObject finalData=data;SwingUtilities.invokeLater(()->render(finalData,now));
        }catch(Exception ex){SwingUtilities.invokeLater(()->connectionLabel.setText("● Verbindung unterbrochen · "+safe(ex)));}}
    private void record(String key,double value,long ts){if(Double.isFinite(value))history.record(key.startsWith("plug.")?key:siteKey(key),ts,value);}
    private String siteKey(String key){return selectedSite+"|"+key;}
    private void pollMyStrom(){String ip=prefs.getString("mystrom_ip","").trim();if(ip.isEmpty())return;try{HttpURLConnection c=(HttpURLConnection)new URL("http://"+ip+"/report").openConnection();c.setConnectTimeout(2200);c.setReadTimeout(2200);try{JSONObject report=new JSONObject(new String(c.getInputStream().readAllBytes(),StandardCharsets.UTF_8));double watts=num(report,"power");if(Double.isFinite(watts)){history.record(siteKey("mystrom."+ip),System.currentTimeMillis(),watts);SwingUtilities.invokeLater(()->{if(myStromStatus!=null)myStromStatus.setText(String.format(Locale.GERMANY,"● %.0f W",watts));if(myStromChart!=null)myStromChart.refresh();});}}finally{c.disconnect();}}catch(Exception ex){SwingUtilities.invokeLater(()->{if(myStromStatus!=null)myStromStatus.setText("Steckdose nicht erreichbar");});}}
    private boolean validIPv4(String ip){String[] p=ip.split("\\.",-1);if(p.length!=4)return false;try{for(String part:p){if(part.isEmpty()||part.length()>3)return false;int n=Integer.parseInt(part);if(n<0||n>255)return false;}return true;}catch(NumberFormatException e){return false;}}
    private void recordPlugs(long ts){for(int i=0;i<devices.length();i++){JSONObject d=devices.optJSONObject(i);if(d==null||!isPlug(d))continue;String sn=first(d,"device_sn","sn");JSONObject live=readMqtt(sn);double watts=num(live,"power","active_power","output_power","real_power");record("plug."+sn,watts,ts);}}
    private JSONObject findMqtt(String pn){for(int i=0;i<devices.length();i++){JSONObject d=devices.optJSONObject(i);if(d!=null&&pn.equalsIgnoreCase(first(d,"device_pn","product_code","device_model")))return readMqtt(first(d,"device_sn","sn"));}return null;}
    private JSONObject readMqtt(String sn){try{return new JSONObject(prefs.getString("mqtt_device_"+sn,"{}"));}catch(Exception e){return new JSONObject();}}
    private void render(JSONObject data,long at){scene=data;connectionLabel.setText("● Verbunden · Live MQTT / Anker Cloud");updatedLabel.setText("Aktualisiert · "+new SimpleDateFormat("dd.MM.yyyy HH:mm:ss",Locale.GERMANY).format(new Date(at)));JSONObject bank=data.optJSONObject("solarbank_info");if(bank==null)bank=new JSONObject();JSONObject grid=data.optJSONObject("grid_info");if(grid==null)grid=new JSONObject();double net=num(grid,"grid_power_signed"),gridIn=num(grid,"grid_to_home_power"),gridOut=num(grid,"photovoltaic_to_grid_power");if(!Double.isFinite(gridIn))gridIn=Double.isFinite(net)?Math.max(0,net):Double.NaN;if(!Double.isFinite(gridOut))gridOut=Double.isFinite(net)?Math.max(0,-net):Double.NaN;double[] m={num(bank,"total_photovoltaic_power","total_pv_input_power"),num(bank,"total_battery_power_signed","total_charging_power"),num(data,"home_load_power"),gridIn,gridOut};for(int i=0;i<metricValues.size();i++)metricValues.get(i).setText(power(m[i]));refreshCards();renderDevices(data);renderPlugs();page.revalidate();page.repaint();}
    private void refreshCards(){if(energyCard!=null)energyCard.refresh();if(batteryCard!=null)batteryCard.refresh();if(meterPowerCard!=null)meterPowerCard.refresh();if(meterVoltageCard!=null)meterVoltageCard.refresh();for(GraphCard c:plugCards.values())c.refresh();}
    private void renderDevices(JSONObject data){devicePanel.removeAll();LinkedHashMap<String,JSONObject> all=new LinkedHashMap<>();for(int i=0;i<devices.length();i++){JSONObject d=devices.optJSONObject(i);if(d!=null)all.put(first(d,"device_sn","sn",String.valueOf(i)),d);}for(String serial:all.keySet()){JSONObject d=all.get(serial);JPanel p=cardPanel();p.setLayout(new BorderLayout(8,5));p.setBorder(new EmptyBorder(12,16,12,16));String name=firstOr(d,"Gerät","alias_name","device_name","name","device_pn","product_code");p.add(label(name+"   ·   "+first(d,"device_pn","product_code","device_model",""),15,INK,true),BorderLayout.NORTH);JSONObject live=readMqtt(serial);StringBuilder values=new StringBuilder();Iterator<String> it=live.keys();while(it.hasNext()){String k=it.next();Object v=live.opt(k);if(v instanceof Number&&!k.equals("received_at")){if(values.length()>0)values.append("     ·     ");values.append(human(k)).append("  ").append(String.format(Locale.GERMANY,"%.1f",((Number)v).doubleValue()));}}p.add(label(values.length()==0?"Noch keine MQTT-Messwerte empfangen":values.toString(),12,MUTED,false),BorderLayout.CENTER);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,76));devicePanel.add(p);devicePanel.add(Box.createVerticalStrut(7));}devicePanel.revalidate();devicePanel.repaint();}
    private void renderPlugs(){ArrayList<String> serials=new ArrayList<>();LinkedHashMap<String,String> names=new LinkedHashMap<>();for(int i=0;i<devices.length();i++){JSONObject d=devices.optJSONObject(i);if(d==null||!isPlug(d))continue;String sn=first(d,"device_sn","sn");if(sn.isBlank()||names.containsKey(sn))continue;names.put(sn,firstOr(d,"Smart Plug Gen2","alias_name","device_name","name"));serials.add(sn);}while(serials.size()>2)serials.remove(serials.size()-1);if(!new ArrayList<>(plugCards.keySet()).equals(serials)){plugPanel.removeAll();plugCards.clear();for(String sn:serials){GraphCard c=new GraphCard("▥  "+names.get(sn),new String[]{"plug."+sn},new String[]{"Leistung"},new Color[]{GREEN},"power");plugCards.put(sn,c);plugPanel.add(c);}}for(GraphCard c:plugCards.values())c.refresh();plugPanel.revalidate();plugPanel.repaint();}
    private void startMqtt(){if(mqtt!=null)mqtt.stop();worker.execute(()->{try{JSONObject info=client.getMqttInfo();AnkerMqttLiveClient live=new AnkerMqttLiveClient(prefs,info,devices,status->SwingUtilities.invokeLater(()->{if(connectionLabel!=null)connectionLabel.setText("● "+status);}));mqtt=live;live.start();}catch(Exception ex){SwingUtilities.invokeLater(()->connectionLabel.setText("● MQTT nicht verfügbar · Cloud-Polling aktiv"));}});}

    private static JSONArray mergeDevices(JSONArray a,JSONArray b){LinkedHashMap<String,JSONObject> map=new LinkedHashMap<>();for(JSONArray src:new JSONArray[]{a,b})for(int i=0;i<src.length();i++){JSONObject d=src.optJSONObject(i);if(d!=null)map.put(first(d,"device_sn","sn",String.valueOf(i)),d);}JSONArray out=new JSONArray();for(JSONObject d:map.values())out.put(d);return out;}
    private static boolean isPlug(JSONObject d){String model=(first(d,"device_pn","product_code","device_model","device_name","name")+" "+first(d,"alias_name","device_name","name")).toUpperCase(Locale.ROOT);return model.contains("A17X8")||(model.contains("SMART PLUG")&&(model.contains("GEN2")||model.contains("GEN 2")));}
    private static String first(JSONObject o,String...keys){for(String k:keys){String s=o.optString(k,"");if(!s.isBlank()&&!s.equals("null"))return s;}return "";}
    private static String firstOr(JSONObject o,String fallback,String...keys){String value=first(o,keys);return value.isEmpty()?fallback:value;}
    private static double num(JSONObject o,String...keys){for(String k:keys){Object v=o.opt(k);if(v instanceof Number)return ((Number)v).doubleValue();if(v!=null)try{double n=Double.parseDouble(String.valueOf(v));if(Double.isFinite(n))return n;}catch(Exception ignored){}}return Double.NaN;}
    private static String power(double w){if(!Double.isFinite(w))return "—";return Math.abs(w)>=1000?String.format(Locale.GERMANY,"%.2f kW",w/1000):String.format(Locale.GERMANY,"%.0f W",w);}
    private static String energy(double w){return power(w);}
    private static String human(String s){return s.replace('_',' ').replaceAll("([a-z])([A-Z])","$1 $2");}
    private static String safe(Exception e){String s=e.getMessage();return s==null?"Fehler":s;}

    private void replaceRoot(JPanel root){frame.setContentPane(root);frame.revalidate();frame.repaint();}
    private JPanel cardPanel(){JPanel p=new JPanel();p.setBackground(CARD);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(BORDER,1,true),new EmptyBorder(10,10,10,10)));return p;}
    private static JLabel label(String s,int size,Color c,boolean bold){JLabel l=new JLabel(s);l.setForeground(c);l.setFont(new Font("SansSerif",bold?Font.BOLD:Font.PLAIN,size));return l;}
    private static void styleInput(JTextField f){f.setMaximumSize(new Dimension(Integer.MAX_VALUE,42));f.setPreferredSize(new Dimension(350,42));f.setBackground(new Color(8,19,32));f.setForeground(INK);f.setCaretColor(GREEN);f.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(BORDER),new EmptyBorder(8,11,8,11)));}
    private static void styleButton(JButton b,Color c){b.setForeground(INK);b.setBackground(c);b.setFocusPainted(false);b.setBorder(new EmptyBorder(8,14,8,14));}

    private final class GraphCard extends JPanel {final String title;final String[] keys,labels;final Color[] colors;final String kind;final Plot plot=new Plot();String range="Tag";GraphCard(String title,String[] keys,String[] labels,Color[] colors,String kind){super(new BorderLayout(8,8));this.title=title;this.keys=keys;this.labels=labels;this.colors=colors;this.kind=kind;setBackground(CARD);setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(BORDER,1,true),new EmptyBorder(13,16,14,16)));JPanel head=new JPanel(new BorderLayout());head.setOpaque(false);head.add(label(title,15,INK,true),BorderLayout.WEST);JPanel buttons=new JPanel(new FlowLayout(FlowLayout.RIGHT,5,0));buttons.setOpaque(false);for(String r:new String[]{"Tag","Monat","Jahr"}){JButton b=new JButton(r);styleButton(b,r.equals(range)?new Color(8,108,155):new Color(24,43,64));b.addActionListener(e->{range=r;for(Component c:buttons.getComponents())if(c instanceof JButton)styleButton((JButton)c,((JButton)c).getText().equals(range)?new Color(8,108,155):new Color(24,43,64));refresh();});buttons.add(b);}head.add(buttons,BorderLayout.EAST);add(head,BorderLayout.NORTH);plot.setPreferredSize(new Dimension(800,205));plot.setBackground(CARD);add(plot,BorderLayout.CENTER);refresh();}void refresh(){ArrayList<double[]> series=new ArrayList<>();for(String key:keys)series.add(history.series(key.startsWith("plug.")?key:siteKey(key),range));plot.setData(series,labels,colors,kind,range);}}

    private final class Plot extends JPanel {List<double[]> series=List.of();String[] labels=new String[0];Color[] colors=new Color[0];String kind="power";String range="Tag";void setData(List<double[]> d,String[] l,Color[] c,String k,String r){series=d;labels=l;colors=c;kind=k;range=r;repaint();}@Override protected void paintComponent(Graphics graphics){super.paintComponent(graphics);Graphics2D g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int left=60,right=getWidth()-15,top=10,bottom=getHeight()-38;double max=.1;for(double[] a:series)for(double v:a)if(Double.isFinite(v))max=Math.max(max,Math.abs(v));double step=kind.equals("percent")?25:Math.pow(10,Math.floor(Math.log10(max)));if(kind.equals("percent"))max=100;else{if(max/step>5)step*=2;if(max/step>4)step*=2;max=Math.ceil(max/step)*step;}g.setStroke(new BasicStroke(1));g.setFont(new Font("SansSerif",Font.PLAIN,11));for(int i=0;i<5;i++){int y=top+(bottom-top)*i/4;g.setColor(new Color(35,57,79));g.drawLine(left,y,right,y);double val=kind.equals("percent")?(4-i)*25:kind.equals("voltage")?(4-i)*max/4:(2-i)*max/2;String text=kind.equals("percent")?String.format("%.0f%%",val):kind.equals("voltage")?String.format("%.0f V",val):power(val);g.setColor(MUTED);g.drawString(text,3,y+4);}int count=series.stream().mapToInt(a->a.length).max().orElse(0);for(int n=0;n<series.size();n++){double[] a=series.get(n);g.setColor(colors[n]);g.setStroke(new BasicStroke(2.2f,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));Path2DLike path=new Path2DLike();boolean opened=false;for(int i=0;i<a.length;i++){if(!Double.isFinite(a[i])){opened=false;continue;}int x=left+(right-left)*i/Math.max(1,a.length-1);int y;if(kind.equals("percent"))y=bottom-(int)((bottom-top)*Math.max(0,Math.min(100,a[i]))/100);else if(kind.equals("voltage"))y=bottom-(int)((bottom-top)*Math.max(0,a[i])/max);else y=top+(int)((bottom-top)*(1-(Math.max(-max,Math.min(max,a[i]))/max+1)/2));if(!opened){path.move(x,y);opened=true;}else path.line(x,y);}g.draw(path.path);}g.setFont(new Font("SansSerif",Font.PLAIN,10));String[] xlabels=rangeLabels(count);g.setColor(MUTED);g.drawString(xlabels[0],left,bottom+18);String mid=xlabels[1];g.drawString(mid,(left+right-g.getFontMetrics().stringWidth(mid))/2,bottom+18);String end=xlabels[2];g.drawString(end,right-g.getFontMetrics().stringWidth(end),bottom+18);int x=left;for(int i=0;i<labels.length;i++){g.setColor(colors[i]);g.fillOval(x,bottom+25,8,8);g.setColor(INK);g.drawString(labels[i],x+12,bottom+33);x+=g.getFontMetrics().stringWidth(labels[i])+35;}g.dispose();}private String[] rangeLabels(int count){if("Tag".equals(range))return new String[]{"00:00","12:00","24:00"};if("Monat".equals(range))return new String[]{"01.","15.","Monatsende"};return new String[]{"Jan","Jun","Dez"};}}
    private final class Path2DLike {final java.awt.geom.Path2D.Float path=new java.awt.geom.Path2D.Float();void move(int x,int y){path.moveTo(x,y);}void line(int x,int y){path.lineTo(x,y);}}

    private final class HistoryStore {final File file=new File(new File(System.getProperty("user.home"),".sonnenbank"),"history.tsv");final Map<String,TreeMap<Long,Double>> rows=new HashMap<>();HistoryStore(){if(file.exists())try(BufferedReader r=new BufferedReader(new FileReader(file))){String line;long cutoff=System.currentTimeMillis()-400L*86400000L;while((line=r.readLine())!=null){String[] p=line.split("\\t");if(p.length!=3)continue;long t=Long.parseLong(p[0]);if(t<cutoff)continue;rows.computeIfAbsent(p[1],k->new TreeMap<>()).put(t,Double.parseDouble(p[2]));}}catch(Exception ignored){}}synchronized void record(String key,long timestamp,double value){long minute=timestamp/60000*60000;TreeMap<Long,Double> data=rows.computeIfAbsent(key,k->new TreeMap<>());Double old=data.put(minute,value);if(old!=null&&Math.abs(old-value)<.01)return;file.getParentFile().mkdirs();try(FileWriter w=new FileWriter(file,true)){w.write(minute+"\t"+key+"\t"+value+"\n");}catch(IOException ignored){}}synchronized double[] series(String key,String range){TreeMap<Long,Double> all=rows.get(key);if(all==null)return new double[0];Calendar now=Calendar.getInstance(),start=(Calendar)now.clone();int slots;if("Tag".equals(range)){slots=288;start.set(Calendar.HOUR_OF_DAY,0);}else if("Monat".equals(range)){slots=now.getActualMaximum(Calendar.DAY_OF_MONTH);start.set(Calendar.DAY_OF_MONTH,1);}else{slots=12;start.set(Calendar.MONTH,Calendar.JANUARY);start.set(Calendar.DAY_OF_MONTH,1);}start.set(Calendar.HOUR_OF_DAY,0);start.set(Calendar.MINUTE,0);start.set(Calendar.SECOND,0);start.set(Calendar.MILLISECOND,0);double[] sums=new double[slots];int[] counts=new int[slots];for(Map.Entry<Long,Double> e:all.tailMap(start.getTimeInMillis(),true).entrySet()){Calendar c=Calendar.getInstance();c.setTimeInMillis(e.getKey());int slot="Tag".equals(range)?(c.get(Calendar.HOUR_OF_DAY)*60+c.get(Calendar.MINUTE))/5:"Monat".equals(range)?c.get(Calendar.DAY_OF_MONTH)-1:c.get(Calendar.MONTH);if(slot>=0&&slot<slots){sums[slot]+=e.getValue();counts[slot]++;}}double[] out=new double[slots];for(int i=0;i<slots;i++)out[i]=counts[i]==0?Double.NaN:sums[i]/counts[i];return out;}}
}
