plugins {
    id 'com.android.application'
}

android {
    namespace 'de.codex.solarbanklive'
    compileSdk 36

    defaultConfig {
        applicationId 'de.codex.solarbanklive'
        minSdk 26
        targetSdk 35
        versionCode 72
        versionName '1.71'
    }

    buildFeatures { buildConfig true }

}
