plugins {
    id 'com.android.application'
}

android {
    namespace 'de.codex.solarbanklive'
    compileSdk 36

    defaultConfig {
        applicationId 'de.codex.solarbanklive'
        minSdk 26
        targetSdk 35
        versionCode 67
        versionName '1.66'
    }

    buildFeatures { buildConfig true }

    flavorDimensions 'layout'
    productFlavors {
        full {
            dimension 'layout'
            buildConfigField 'boolean', 'SIMPLE_OVERVIEW', 'false'
        }
        overview {
            dimension 'layout'
            applicationIdSuffix '.overview'
            versionNameSuffix '-overview'
            buildConfigField 'boolean', 'SIMPLE_OVERVIEW', 'true'
        }
    }
}
